version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: cogni-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=CogniDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cogni-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cogni-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cogni-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    container_name: cogni-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - cogni-network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.0
    container_name: cogni-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - cogni-network

  processing-service:
    build:
      context: .
      dockerfile: src/Services/ProcessingService/Dockerfile
    container_name: cogni-processing-service
    environment:
      - AI__GeminiKey=${GEMINI_API_KEY}
      - AI__GeminiModelId=${GEMINI_MODEL_ID}
      - Elasticsearch__Uri=http://elasticsearch:9200
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
      - FileStorage__UploadPath=/app/uploads
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - cogni-network
    volumes:
      - ./uploads:/app/uploads

  document-service:
    build:
      context: .
      dockerfile: src/Services/DocumentService/Dockerfile
    container_name: cogni-document-service
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=CogniDb;Username=admin;Password=Password123!
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
      - FileStorage__UploadPath=/app/uploads
      - FileStorage__AllowedExtensions=.pdf,.txt,.docx
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5001:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - cogni-network

networks:
  cogni-network:
    driver: bridge

volumes:
  postgres_data:
  elastic_data:
