version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cogni-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=CogniDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: