version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cogni-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=CogniDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:3-management-alpine # The ‘management’ tag for admin panel (UI)
    container_name: cogni-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"   # Applications connect here
      - "15672:15672" # Access the management panel from your browser here

volumes:
  postgres_data: